"""add_is_autopay

Revision ID: 139133b3a526
Revises: c8e1f4a2b790
Create Date: 2026-08-15 18:52:46.811321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '139133b3a526'
down_revision = 'c8e1f4a2b790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('is_color_auto',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('expected_expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_autopay', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expected_expense', schema=None) as batch_op:
        batch_op.drop_column('is_autopay')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('is_color_auto',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
